services:
  mkdocs:
    image: stresssimple/docs
    build:
      context: ./docs
      dockerfile: Dockerfile

    volumes:
      - ./docs:/app/docs
    command: bash -c "/app/run.sh"
    ports:
      - 8000:8000
