auth:
  enabled: true
  # service:
  # type: LoadBalancer
  # LoadBalancerIP: 192.168.220.2
  # global:
  #   storageClass: nfs-fast
image:
  registry: docker.io
  repository: bitnami/mysql
  tag: 9.0.1-debian-12-r10
ingress:
  enabled: true
  hostname: rabbitmq.k8s.home
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: infra
          operator: In
          values:
          - "true"
initdbScripts:
  my_init_script.sh: |
    #!/bin/bash
    if [[ $(hostname) == *primary* ]]; then
      echo "Primary node"
      password_aux="${MYSQL_ROOT_PASSWORD:-}"
      if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
          password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
      fi
      mysql -P 3306 -uroot -p"$password_aux" -e "create database new_database";
    else
      echo "Secondary node"
    fi  
