auth:
  enabled: true
  # service:
  # type: LoadBalancer
  # LoadBalancerIP: 192.168.220.2
  # global:
  #   storageClass: nfs-fast
tolerations:
- key: "kubernetes.azure.com/scalesetpriority"
  operator: "Equal"
  value: "spot"
  effect: "NoSchedule"
nodeSelector:
  agentpool: infra
