name: Docker Image CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  # allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and push the Docker image
        run: |
          TIMESTAMP=$(date +%s)
          docker build backend/ --file backend/Dockerfile --tag backend:$TIMESTAMP
          docker tag backend:$TIMESTAMP ghcr.io/hananmil/stressjs/backend:$TIMESTAMP
          docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ghcr.io/hananmil/stressjs/backend:$TIMESTAMP
          echo "::set-output name=image::ghcr.io/hananmil/stressjs/backend:$TIMESTAMP"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
