name: Build and push Frontend Docker image

on:
  push:
    branches: ["master"]
    paths:
      - "front/**"
  pull_request:
    branches: ["master"]
    paths:
      - "front/**"
  # allow manual trigger
  workflow_dispatch:
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  # allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and push the Docker image
        run: |
          TIMESTAMP=$(date +%s)
          IMAGE_NAME=ghcr.io/hananmil/stressjs/front

          # Build the image with the timestamp tag
          docker build front/ --file front/Dockerfile --tag front:$TIMESTAMP
          docker tag front:$TIMESTAMP $IMAGE_NAME:$TIMESTAMP

          # Login to GitHub Container Registry
          docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}

          # Push the timestamped image
          docker push $IMAGE_NAME:$TIMESTAMP

          # Check if the current branch is master
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            # Tag and push as 'latest'
            docker tag front:$TIMESTAMP $IMAGE_NAME:latest
            docker push $IMAGE_NAME:latest
            echo "Image tagged and pushed as latest"
          fi

          echo "::set-output name=image::$IMAGE_NAME:$TIMESTAMP"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
