name: Build and push Frontend Docker image

on:
  push:
    branches: ["master"]
    paths:
      - "front/**"
      - ".github/workflows/front.yml"
  pull_request:
    branches: ["master"]
    paths:
      - "front/**"
      - ".github/workflows/front.yml"
  # allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and push the Docker image
        run: |
          TIMESTAMP=$(date +%s)
          IMAGE_NAME=ghcr.io/stresssimple/front

          echo $GITHUB_TOKEN | docker login ghcr.io -u USERNAME --password-stdin
          docker login ghcr.io -u USERNAME -p ${{ secrets.GITHUB_TOKEN }}

          # Build the image with the timestamp tag
          docker build front/ --file front/Dockerfile --tag $IMAGE_NAME:$TIMESTAMP


          # Push the timestamped image
          docker push $IMAGE_NAME:$TIMESTAMP

          # Check if the current branch is master
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            # Tag and push as 'latest'
            docker tag $IMAGE_NAME:$TIMESTAMP $IMAGE_NAME:latest
            docker push $IMAGE_NAME:latest
            echo "Image tagged and pushed as latest"
          fi

          echo "::set-output name=image::$IMAGE_NAME:$TIMESTAMP"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
